### ISSUE TITLE
Path in Downloader window not visible, colors too similar

### ISSUE THREAD

**Issue by daPhipz** [quickemu-project/quickgui#101]
Hello!
The path where VMs will be stored is invisible in the Downloader, see attached screenshot.
Thanks!

![grafik](https://user-images.githubusercontent.com/30795174/210677028-5b076331-dcba-47e1-a91e-b55752b9ae7d.png)

**Comment by daPhipz** [comment]
...btw, I noticed some untranslated strings. How can I update the `po` file for the German translation again? It has been quite a long time since I last contributed to quickgui xD

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickgui/commit/d3fe2c8c4fb396b177c26091c6f972cc255db0dd
