### ISSUE TITLE
No interface icons

### ISSUE THREAD

**Issue by Ashdemai** [quickemu-project/quickgui#103]
Installed on Arch via the quickgui-bin package.
![Screenshot from 2023-03-15 16-41-50](https://user-images.githubusercontent.com/74661175/225344993-f312340c-8263-4398-8912-9fc620ffc322.png)

**Comment by Tater-K7S5A** [comment]
Same issue on Linux Mint 21.1,  It worked initially a few weeks ago.  Now nothing in the window.

**Comment by sandivuk** [comment]
Same here. I used this successfully a couple of weeks ago and now I get a blank screen

**Comment by sandivuk** [comment]
Well I'm not sure what changed but after a bunch of system updates that seemed unrelated, quickgui is now showing icons again

**Comment by Ashdemai** [comment]
Still not showing me any buttons after the update.

**Comment by Tater-K7S5A** [comment]
I opened Quickgui and it was blank.  Until I clicked in the window area and now I can see the interface.  Until I close and reopen it.  then I have to click the window again to get the interface....   I restarted the computer and still the same.  

So at least I have a working interface, albeit with an IQ challenge to gain access.  Getting closer.

**Comment by delasalle-sio-paulin-i** [comment]
I'm having a similar issue after sometime, part of the UI appears but i'm still missing most of it 
![Screenshot from 2023-11-02 18-24-43](https://github.com/quickemu-project/quickgui/assets/22473209/697fad98-3d28-47da-bc28-db92683abb4f)

**Comment by caiotizio** [comment]
the same for me. empty window on Mint 21.3

**Comment by derkrasseleo** [comment]
Same here on Arch
