### ISSUE TITLE
Please add a Windows option

### ISSUE THREAD

**Issue by Phisika1** [quickemu-project/quickgui#107]
Why is Windows not in the list, but its in QuickEMU?

**Comment by lackonius** [comment]
I can second the issue on the missing option to create/add a Windows VM. I'm running version 1.2.8-1 and the 'OPERATING SYSTEM' select list doesn't include a Windows option.  

The steps below on manually downloading can be used as a workaround.

1. Open a terminal window and `cd` to the directory where machines are stored (this is displayed in various screens inside of quickqui)
2. Manually run `quickget windows 11` or whatever version of Windows you want to create
3. Once done (message on how to start the VM will display) you can open Quickemu, manage an existing VM, and the new Windows VM will be there.
    - You may need to close quickgui and re-open if it was already open in order for the new VM to appear

**Comment by TuxVinyards** [comment]
I wouldn't normally want to comment on issues in this repository, however as similar issue #111  came up in the Discord feed & they started to voice problems with quickemu itself ...

You may wish to try qqX which is an alternate front end to quickgui. This does have Windows listed.

And AFAIK the only VM system that does easily install and boot Windows ...

Give it a try?

https://github.com/TuxVinyards/qqX
