### ISSUE TITLE
Windows Is Missing from QuickGui Operating System Dropdown

### ISSUE THREAD

**Issue by RaymondTheBrave0** [quickemu-project/quickgui#111]
I have just installed quickemu and quickgui on Linux Mint 21 and have come across the issue of the Windows operating systems are not listed in the dropdown box in the quickgui.

 I have managed to download Zorin 16 as an example but I would like to install Windows 11.

**Comment by RaymondTheBrave0** [comment]
I am currently using quickget to download Windows 11 which seems to be working. I will come back and update issue.

**Comment by dylanvdmerwe** [comment]
Just installed on Ubuntu, and Windows is not an option from the GUI.

**Comment by RaymondTheBrave0** [comment]
Thanks for your reply. I have decided not to use virt-manager etc and stay with Virtualbox as I found it difficult to get the display of any operating system to come out correctly and the mouse control was erractic and how to move from the VM to the host.

**Comment by TuxVinyards** [comment]
@RaymondTheBrave0  I wouldn't normally want to comment on this issues in this repository, however as your issue came up in the Discord feed & you have voiced problems with quickemu itself ...

You may wish to try qqX which is an alternate front end to quickgui.  This does have Windows listed.

And AFAIK the only VM system that does easily install and boot Windows ...

Give it a try?

**Comment by TuxVinyards** [comment]
https://github.com/TuxVinyards/qqX

**Comment by RaymondTheBrave0** [comment]
Thanks I will try.  It as having a Windows 11 installation that does not need a email address and it uses a local user is so much better.

**Comment by RaymondTheBrave0** [comment]
I am running Cinnamon on Linux Mint 21.
qqX needs quickmenu installed but the Ubuntu 22.04 install  command is "quickget ubuntu-mate 22.04 which is not working as I dont have quickget. I assume because IU have already removed qemu etc. I am
So what do I need to install to be able to install qqX? If you can just list the steps I should be able to install it.

**Comment by TuxVinyards** [comment]
@RaymondTheBrave0  Pleased to see you having a try & sorry if my instructions are not clear.   

"Start the set up with original quickemu as normal. https://github.com/quickemu-project/quickemu "

Please read this as:  Set up your computer in the normal way, as if you are installing the whole quickemu package, complete with all its components and all its dependencies, as in the instructions on the quickemu-project pages"

I will amend the qqX readme ...  So thank you for saying you had problems & sorry again.  This will all help the improve the project. :+1: 

After you have downloaded and installed qqX,  this will  wrap both the quickemu & quickget scripts.   And quickemu will wrap Qemu and KVM etc

I suggest that you start by installing a basic linux distro first.  Something that you are familiar with.  Perhaps a Mint variant?  This will then tell you that your setup is working correctly. 

When it comes to installing Windows,  the practice  with the Linux install will hold you in good stead.  There are details on the quickemu about the initial boot procedures, like spamming the enter key at the right points.  Quickemu  adds in quite a few behind the scenes shims to make things easy.  But it is still not as easy and as straight forward as with Linux ....

Good Luck.   Let me know how you get on.
I

**Comment by RaymondTheBrave0** [comment]
Hi,

I am already running Linux Mint 21 on a dual boot machine and have done for over a year now. I try and use Mint most of the time. 

1. I have run this command and it worked sudo apt install qemu bash coreutils ovmf grep jq lsb-base procps python3 genisoimage usbutils util-linux sed spice-client-gtk libtss2-tcti-swtpm0 wget xdg-user-dirs zsync unzip

2. But when I got to sudo apt install quickemu it could not find quickgui. I did issue the sudo add-apt-repository ppa:yannick-mauray/quickgui command and the sudo apt update command first.

Is Linux Mint 21 support as it is based on Ubuntu 22.04 I think?

**Comment by TuxVinyards** [comment]
Quickemu and Quickgui are separate projects, as is qqX.     Both Quickgui & qqX are front ends for quickemu, of which you can use one or the other or both.  Or neither.  But you must have the quickemu package. 

I have just updated the qqX install instructions, again, this morning. Have a re-read.
