### ISSUE TITLE
bug: Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

### ISSUE THREAD

**Issue by AgostinoA** [quickemu-project/quickgui#112]
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(57)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

Does anyone know how to solve this problem?
I'm using the Focal version

**Comment by flexiondotorg** [comment]
Tested on Ubuntu 22.04 and Ubuntu 24.04 with the Quickgui 1.2.9 release candidate and this issue is not presented. Fixed via https://github.com/quickemu-project/quickgui/commit/dad70f24f6c7ba1030b42fae6ff8cd8458575874
