### ISSUE TITLE
flutter_localizations depends on intl 0.18.1 and quickgui depends on intl ^0.17.0

### ISSUE THREAD

**Issue by Somnius** [quickemu-project/quickgui#121]
_Because every version of flutter_localizations from sdk depends on intl 0.18.1 and quickgui depends on intl ^0.17.0, flutter_localizations from sdk is forbidden._

_You can try the following suggestion to make the pubspec resolve:_
_* Try upgrading your constraint on intl: flutter pub add intl:^0.18.1_

**Comment by Darkpepito** [comment]
Hey,  
Just like the message says, to fix it you just have to run :  
`flutter pub add intl:^0.18.1`

**Comment by Schweeeeeeeeeeeeeeee** [comment]
same problem
@Darkpepito command doesent fix it for me

**Comment by liguopengbenli** [comment]
same problem

**Comment by martin-braun** [comment]
This project doesn't really have any extern dependencies that it forces it to be constantly up2date with the Flutter releases. My suggestion instead is to add an `.fvmrc` that points to the right version of Flutter, so the project can continue to build without any interference by Flutter releases.

https://fvm.app/

Let's just lock it?

I downgraded by simply running `fvm use 3.7.12` and then I could build with `make FLUTTER="fvm flutter" ...`.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickgui/commit/d7f962fe4c0bb2453ea158423a662bcc451096f0
