### ISSUE TITLE
Can't change the directory where the VMs get stored

### ISSUE THREAD

**Issue by SebastianStork** [quickemu-project/quickgui#122]
I can't change the directory where new VMs get stored and quickgui looks for existing ones. When I click on the current path (/home/seb for me) nothing happens. 

I am using the window manager qtile (X11). My distro is NixOS and I'm running the latest release, installed through the nix package manager. 

Thanks for the help and your time.

**Comment by Samueru-sama** [comment]
Same issue here on artix with i3wm.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickgui/pull/130 which makes sure `zenity` is included as a dependency.
