### ISSUE TITLE
bug: quickgui encounters X Window System error when executed

### ISSUE THREAD

**Issue by s-b-repo** [quickemu-project/quickgui#126]
(quickgui:279493): Gdk-ERROR **: 15:17:21.558: The program 'quickgui' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 595 error_code 2 request_code 152 (GLX) minor_code 22)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

**Comment by s-b-repo** [comment]
Thread 1 "quickgui" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff6225167 in g_log_writer_default () from /lib/x86_64-linux-gnu/libglib-2.0.so.

**Comment by s-b-repo** [comment]
#include <X11/Xlib.h>
#include <stdio.h>

Display *d;
XErrorEvent error;

int xErrorHandler(Display *d, XErrorEvent *error) {
    char errorMessage[256];
    XGetErrorText(d, error->error_code, errorMessage, sizeof(errorMessage));
    fprintf(stderr, "X Error: %s\n", errorMessage);
    return 0;
}

int main() {
    d = XOpenDisplay(NULL);
    if (d == NULL) {
        fprintf(stderr, "Cannot open display\n");
        return 1;
    }

    XSetErrorHandler(xErrorHandler);

    // Your X-related code here

    XCloseDisplay(d);
    return 0;
}

**Comment by s-b-repo** [comment]
serial 595 error_code 2 request_code 152 (GLX) minor_code 22

provides some detailed information:

    serial 595: This is the serial number of the request that caused the error.
    error_code 2: This corresponds to BadValue, indicating an invalid parameter was passed.
    request_code 152 (GLX): This is the X request code for GLX operations.
    minor_code 22: This is the specific GLX request that failed.

**Comment by flexiondotorg** [comment]
Tested on Ubuntu 22.04 and Ubuntu 24.04 with the Quickgui 1.2.9 release candidate and this issue is not presented. Fixed via https://github.com/quickemu-project/quickgui/commit/dad70f24f6c7ba1030b42fae6ff8cd8458575874
