### ISSUE TITLE
bug: failed to read XDG desktop portal settings: 

### ISSUE THREAD

**Issue by s-b-repo** [quickemu-project/quickgui#127]
(quickgui:36019): CRITICAL **: 01:36:59.826: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (quickgui:36019): CRITICAL **: 01:36:59.827: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (quickgui:36019): CRITICAL **: 01:36:59.827: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (quickgui:36019): CRITICAL **: 01:36:59.828: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (quickgui:36019): CRITICAL **: 01:36:59.828: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): null is not a String or Directory
#0      _Directory.current= (dart:io/directory_impl.dart:62)
#1      Directory.current= (dart:io/directory.dart:168)
#2      _DownloaderMenuState.build.<anonymous closure>.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:58)
#3      State.setState (package:flutter/src/widgets/framework.dart:1114)
#4      _DownloaderMenuState.initState.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:24)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): null is not a String or Directory
#0      _Directory.current= (dart:io/directory_impl.dart:62)
#1      Directory.current= (dart:io/directory.dart:168)
#2      _DownloaderMenuState.build.<anonymous closure>.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:58)
#3      State.setState (package:flutter/src/widgets/framework.dart:1114)
#4      _DownloaderMenuState.initState.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:24)
<asynchronous suspension>

(quickgui:36019): GLib-GObject-CRITICAL **: 01:37:49.761: ../glib/gobject/gsignal.c:2685: instance '0x3e4c6ec0' has no handler with id '268'
[lolilover@lolilover-systemproductname ~]$ sudo quickgui
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): null is not a String or Directory
#0      _Directory.current= (dart:io/directory_impl.dart:62)
#1      Directory.current= (dart:io/directory.dart:168)
#2      _DownloaderMenuState.build.<anonymous closure>.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:58)
#3      State.setState (package:flutter/src/widgets/framework.dart:1114)
#4      _DownloaderMenuState.initState.<anonymous closure> (package:quickgui/src/widgets/home_page/downloader_menu.dart:24)
<asynchronous suspension>

flutter: Failed to find definition for #a
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1204)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1023)
flutter: #2      reportMissingDef (package:flutter_svg/src/utilities/errors.dart:5)
flutter: #3      _Elements.linearGradient (package:flutter_svg/src/svg/parser_state.dart:395)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:854)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:131)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:84)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: No such file or directory, errno = 2), address = /run/user/0/bus, port = 0
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:948)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1815)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21)
#4      DBusClient._openSocket (package:dbus/src/dbus_client.dart:768)
#5      DBusClient._connect (package:dbus/src/dbus_client.dart:788)
#6      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
#7      DBusClient.getNameOwner (package:dbus/src/dbus_client.dart:449)
#8      DBusClient._findUniqueName (package:dbus/src/dbus_client.dart:625)
#9      DBusSignalStream._onListen (package:dbus/src/dbus_client.dart:132)
#10     _runGuarded (dart:async/stream_controller.dart:814)
#11     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207)
#12     _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
#13     _StreamImpl.listen (dart:async/stream_impl.dart:471)
#14     DBusSignalStream.listen (package:dbus/src/dbus_client.dart:125)
#15     NotificationsClient._subscribeSignals (package:desktop_notifications/src/notifications_client.dart:343)
#16     NotificationsClient.notify (package:desktop_notifications/src/notifications_client.dart:257)
#17     _DownloaderState.progressStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:quickgui/src/pages/downloader.dart:104)
#18     State.setState (package:flutter/src/widgets/framework.dart:1114)
#19     _DownloaderState.progressStream.<anonymous closure>.<anonymous closure> (package:quickgui/src/pages/downloader.dart:102)
<asynchronous suspension>

**Comment by flexiondotorg** [comment]
Tested on Ubuntu 22.04 and Ubuntu 24.04 with the Quickgui 1.2.9 release candidate and this issue is not presented. Fixed via https://github.com/quickemu-project/quickgui/commit/dad70f24f6c7ba1030b42fae6ff8cd8458575874
