### ISSUE TITLE
bug: quickgui is not available in the PPA for Ubuntu 24.04

### ISSUE THREAD

**Issue by vudutech** [quickemu-project/quickgui#149]
When running
sudo add-apt-repository ppa:yannick-mauray/quickgui
sudo apt update

The following error is produced:-
Err:15 https://ppa.launchpadcontent.net/yannick-mauray/quickgui/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
W: https://ppa.launchpadcontent.net/flexiondotorg/quickemu/ubuntu/dists/noble/InRelease: Signature by key 824A27DD09DEDA33BF7835962EA8F35793D8809A uses weak algorithm (rsa1024)
E: The repository 'https://ppa.launchpadcontent.net/yannick-mauray/quickgui/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Thanks

**Comment by flexiondotorg** [comment]
I am currently working on preparing a release of Quickgui 1.2.9 which will include support for recent Ubuntu releases.

**Comment by flexiondotorg** [comment]
Packages are currently building in the Quickemu PPA:

- <https://launchpad.net/~flexiondotorg/+archive/ubuntu/quickemu>

Fixed via https://github.com/quickemu-project/quickgui/releases/tag/1.2.9

**Comment by vudutech** [comment]
Thanks had a couple more errors, easily fixed.

sudo dpkg -i quickgui-1.2.9+1-linux.deb

dpkg: dependency problems prevent configuration of quickgui:
 quickgui depends on zenity; however:
  Package zenity is not installed.

  dpkg: error processing package quickgui (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 quickgui

 sudo apt --fix-broken install

All good now. Thanks for your effort and super usefull app.

**Comment by flexiondotorg** [comment]
The [README clearly documents you should use `apt-get` to install the .deb](https://github.com/quickemu-project/quickgui#debian), not `dpkg`. `apt-get` will install the dependencies without issue, but `dpkg -i` will not.
