### ISSUE TITLE
bug: [macos_desktop] active VMs are not detected

### ISSUE THREAD

**Issue by ymauray** [quickemu-project/quickgui#179]
- [x] I have searched the issues and this bug has not been reported previously

On the macos_desktop branch, quickgui does not detect running VMs, therefore, it is not possible to connect via SSH, or kill the VM, etc..

1. Launch a VM
2. See that the buttons don't appear

Expected behavior:
The control buttons should appear

**Desktop (please complete the following information):**
 - Quickgui Versdion: tip of macos_desktop branch
 - OS: macos on Apple silicon
 - Version: Sonoma 14.5

**Comment by flexiondotorg** [comment]
I know how to fix this. I'll prepare a pull request.
