### ISSUE TITLE
bug: app displays "Waiting for download to start" until download is complete.

### ISSUE THREAD

**Issue by jordan-bravo** [quickemu-project/quickgui#186]
**I confirm this bug has not already been reported**
- [x] I have searched the issues and this bug has not been reported previously

**Describe the bug**
When downloading a VM, the app displays "Waiting for download to start", with an infinitely sliding progress bar.  No progress is shown.  It remains in this state until the download eventually completes.

**To Reproduce**
1. Open app
2. Click "Create new machine"
3. Choose any OS and any version
4. Click "Download"
5. Observe app

**Expected behavior**
When downloading a VM, the app should indicate that the download is in progress with text such as "Downloading..." or "Download in progress...", and ideally the progress bar should actually show the progress, or at the very least a percentage should be displayed.

**Desktop (please complete the following information):**
 - Quickgui Versdion: 1.2.8-1
 - Quickemu version: 4.9.5
 - OS: NixOS 
 - Version: 24.11 (latest unstable)

**Screenshots**

![Screenshot from 2024-07-05 14-42-54](https://github.com/quickemu-project/quickgui/assets/62706808/2289c846-81ea-4a85-92c0-53a8341b0066)

**Comment by lj3954** [comment]
Please update quickgui. Quickgui 1.2.8 does not support the progress indicator of curl that quickget now uses. Fixed in #138
