### ISSUE TITLE
bug: downloading reports success instead of failure when storage is read-only

### ISSUE THREAD

**Issue by gschintgen** [quickemu-project/quickgui#191]
**I confirm this bug has not already been reported**
- [x] I have searched the issues and this bug has not been reported previously

**Describe the bug**
When the storage directory for the virtual machines is accidentally read-only (e.g. new mountpoint, still owned by root), downloading an image will seemingly start correctly, but after a second or so it terminates with a notification about a successful download.

**To Reproduce**
0. Fresh install of quickemu, quickgui
1. as root: Set up a new partition, configure it in fstab, mount it as /home/myuser/virtualmachines
2. in quickgui's "Manager": set the new directory as storage directory
3. in quickgui: "Create new machines", choose a random operating system
4. Click 'Download'
5. Observe "Success" when in fact the download failed.

**Expected behavior**
The failed download should lead to an error message.

**Desktop (please complete the following information):**
 - Quickgui Versdion: [1.2.10-1~jammy24186.1614] (installed from PPA)
 - OS: Ubuntu
 - Version 22.04

**Comment by iEscapedVim** [comment]
Facing the same issue on Arch Linux, with Hyprland QuickGUI Ver. 1.2.10
