### ISSUE TITLE
feat: windows xp and windows 7 VM

### ISSUE THREAD

**Issue by caiotizio** [quickemu-project/quickgui#195]
**I confirm this feature has not been previously requested**
- [x] I have searched the issues and this feature has not previously been requested

hi there, please add windows xp and windows 7 images.
thanks for your work.

**Comment by lj3954** [comment]
Legacy software is out of the scope of the quickemu project. Quickgui also is not where new operating system-type feature requests should be made, quickemu is the tool responsible for such features.
