### ISSUE TITLE
7 Levels of PPA Hell

### ISSUE THREAD

**Issue by FelicianoTech** [quickemu-project/quickgui#196]
Hey friends. I was trying to get this installed via PPA and have been hitting multiple blockers.

1. The readme of this project `quickgui` suggest installing with the following PPA: `ppa:flexiondotorg/quickgui` When I try it, I get a message telling me that the PPA is not found. `add-apt-repository` gives a hint that maybe it's private but I don't know if that is relevant here.
2. The `quickemu` [alternate frontends](https://github.com/quickemu-project/quickemu/wiki/07-Alternative-frontends) doc mentions `quickgui` and how to install it. That doc refers to a different PPA to use (I believe an older one): `ppa:yannick-mauray/quickgui`. That PPA doesn't work for me either. Trying to use it gives me an error about a missing release file and that the repo will be ignored. Basically the error message from this issue: https://github.com/quickemu-project/quickgui/issues/149
3. [This Launchpad page](https://launchpad.net/~flexiondotorg/+archive/ubuntu/quickemu) suggests that both `quickemu` and `quickgui` can be installed with the `quickemu` PPA. That is also not the case for me. `quickemu` installs fine but not this project.

I'm taking this as a personal sign that I should stick to the terminal for now. 😄 

As for some details, I am running Ubuntu Asahi 24.04. I can follow up when I get home to see if any of these issues changes when trying with my Ubuntu 24.04 amd64 machine.

**Comment by philclifford** [comment]
The latest release was made in the quickemu PPA so you should use that one.  It was updated to support 24.04 but I suspect your being on Asahi is where the problem lies.

Meanwhile clearly the wiki page needed an update (done) to point to the right PPA (and `deb-get` needs an update also to repoint the PPA)

**Comment by flexiondotorg** [comment]
Fixed everywhere :slightly_smiling_face:
