### ISSUE TITLE
Add an option to delete VMs?

### ISSUE THREAD

**Issue by diddledani** [quickemu-project/quickgui#20]
I think we're missing an option to delete a VM once we've created it. Thoughts?

**Comment by marxjohnson** [comment]
I did have this thought, the could be a "bin" button next to the play/stop buttons on the manager screen to delete the VM (with a confirmation step).

However, what should this button do? `quickemu --vm vm.conf --delete` exists, but it just deletes the disk image. Should we just be exposing that behaviour, or should we completely delete the VM directory and .conf file?

**Comment by ymauray** [comment]
If we draw a parallel with what a file explorer does, simply "deleting" a file just puts it in the trash, it doesn't remove the file completely.
So I would tend to thing a "delete" button would just delete the disk and variables, leaving the config intact. Maybe the UI could show up an icon or a different color when it does not detect a disk ? That would also bring attention to newly created VMs, when the use comes back from the downloader.

**Comment by flexiondotorg** [comment]
> However, what should this button do? `quickemu --vm vm.conf --delete` exists, but it just deletes the disk image. Should we just be exposing that behaviour, or should we completely delete the VM directory and .conf file?

Perhaps `quickemu` needs to expand the delete functionality?

  * `--delete disk` to just delete the virtual hard drive.
  * `--delete vm` to delete everything.

And deprecate `--delete` to just explain the two options above.

**Comment by marxjohnson** [comment]
Generally speaking, I'm in favour of the principle that the GUI should expose quickemu's functionality, rather than add to it or reimplement it. If we're going to add a "full delete" option, I'd agree with @flexiondotorg's suggestion of adding it to quickemu first.

Regarding the UI, I think something like the below would be good:
![deletion UI mockup](https://user-images.githubusercontent.com/235681/141701732-ca26a3b4-4449-4f01-a9bc-d1b447008070.png)

**Comment by ymauray** [comment]
I have no objection, that sounds like the right thing to do.

**Comment by flexiondotorg** [comment]
I've added `--delete-disk` and `--delete-vm` options to quickemu 2.3.3 which was released earlier today. The existing `--delete` is now an alias for `--delete-disk`.

**Comment by philclifford** [comment]
> @diddledani I've pushed this to branch wip20, give it a go and let me know if you've got any feedback.

It actually got mingled in with #52 last night

**Comment by marxjohnson** [comment]
How embarassing. Oh well, I'm happy enough with how it works for now, Hopefully the changes of someone running with an old version of quickemu are minimal. I'll mark this closed, we can open a new issue for any improvements.

**Comment by ymauray** [comment]
Yeah, sorry I didn't catch that up earlier. I didn't want to mess with my already very messy merge :P

**Comment by marxjohnson** [comment]
@ymauray I dont seem to have permission to close issues, could you grant it for me?

**Comment by ymauray** [comment]
Wimpy made us both owners now :)
