### ISSUE TITLE
bug: bottom of interface cut off (again) for some

### ISSUE THREAD

**Issue by philclifford** [quickemu-project/quickgui#216]
Quickgui 1.2.10. I'm still having this problem.

![image](https://github.com/user-attachments/assets/608b2994-8a06-407d-8c2f-227c9b199caa)

 Pop_os 22.04. Not using wayland

![image](https://github.com/user-attachments/assets/689c1ce3-af06-41ef-a601-469fd87fb00b)

Window can not be resized or maximized

_Originally posted by @glantucan in https://github.com/quickemu-project/quickgui/issues/100#issuecomment-2325564841_

**Comment by glantucan** [comment]
Also happening to me on PopOS

**Comment by glantucan** [comment]
Just installed it on a new computer fresh PopOS 22.04 install. Same thing. Not a big deal form cause I can still use quickemu, but understand this a gui for more or less unexperienced linux users and PopOS seems to be very popular this days as an entry level distro

**Comment by mikey0000** [comment]
Also a problem on Kubuntu, can't create VMs now.

**Comment by marxjohnson** [comment]
I've just found this issue myself, I'm looking in to it.

**Comment by marxjohnson** [comment]
Ok, this is a bit strange.

We have some lines to set the max, min and default window size. When I increase these so that the window is the right size, the actual window size in pixels doesn't seem to bear any apparent relation to the size I set:

![Screenshot from 2024-11-08 14-01-35](https://github.com/user-attachments/assets/87800d57-3d9a-42fd-b3f6-ef115d2b9f02)
![Screenshot from 2024-11-08 14-01-49](https://github.com/user-attachments/assets/953ecc5a-ade7-4568-b8c3-101b32892731)

It could be that I'm making incorrect assumptions about how `Size()` works. @ymauray Do you have any thoughts about this?

**Comment by ymauray** [comment]
@marxjohnson The comments in `main.dart`, on line 76, says the size also needs to be changed in `my_application.cc`.

Could that be what the cause of all your troubles ?

`main.dart`, line 76 :

```dart
  // Don't forget to also change the size in linux/my_application.cc:50
  if (Platform.isMacOS) {
    setWindowMinSize(const Size(692 + 2, 580 + 30));
    setWindowMaxSize(const Size(692 + 2, 580 + 30));
  } else {
    setWindowMinSize(const Size(692, 580));
    setWindowMaxSize(const Size(692, 580));
  }
```

The reason for all those shenanigans is that, depending on the platform, setWinM??Size will or won't take the window decoration into account. Heck, I think on some linux DE, it may or may not do the same thing. May there should be some kind of `if (myDe.behaves()) { ... } else { ... }` code here, for linux. 

`linux/my_application.cc`, lines 50 and 51 :

```c++
  gtk_window_set_default_size(window, 692, 580);
  gtk_widget_show(GTK_WIDGET(window));
```

**Comment by marxjohnson** [comment]
I've been changing the `gtk_window_set_default_size()` call to match the `setWindowMinSize()` call. Same result, the actual minimum window size is much smaller in pixels that the numbers passed to `setWindowMinSize()`, even with decorations.

FWIW, I am current running stock Ubuntu 22.04.
