### ISSUE TITLE
quickgui causes GNOME 41 to hang in Arch Linux x64

### ISSUE THREAD

**Issue by ajacocks** [quickemu-project/quickgui#40]
I'm not sure how to collect troubleshooting data for this issue, but I've got a reproducible hang when launching the download of any VM. The download goes on, of course, but I have to either kill and restart my entire DE or restart the machine.

Confirmed that this also happens using Deepin DE -current. And with KDE Plasma 5.23.

Has anyone else seen this? Clearly, flutter is interacting badly with the WM, somehow, but I don't see anything obvious.

**Comment by WillyJimmyDev** [comment]
Hi. This sounds like a possible replica of issue #28. If so, it has been fixed in the GitHub repo but not released as a PPA. Have you tried the latest code from the repo?
