### ISSUE TITLE
Add --ignore-msrs-always option ?

### ISSUE THREAD

**Issue by matteorizzello** [quickemu-project/quickgui#50]
I had problems starting the VM because using quickgui I had no idea I had to use the --ignore-msrs-always command

**Comment by ymauray** [comment]
Hi, thanks for the comment. 

Running `quickemu --ignore-msrs-always` requires `sudo`. I am not willing to run a `sudo` script from the GUI.

What we will do, is have a message popup after installing a Windows of macOS VM, reminding the user that they may have to run that command.

This will not be implemented right now, but probably early next year.

Thanks again for your contribution.

**Comment by flexiondotorg** [comment]
This is out of scope for the project. You can use `quickemu` to apply `--ignore-msrs-always`
