### ISSUE TITLE
White screen on startup - Pop!_OS 21.04

### ISSUE THREAD

**Issue by TaliskerMan** [quickemu-project/quickgui#51]
I can see the screen when I hover a terminal over the application, but when the application is shown, it appears to be "blank" even though it is not. I've seen this in Firefox when the graphics acceleration is turned on in Firefox, not sure if this is the same in this application. Running my system on GEForce RTX 2070 with a Samsung 4K TV because I have presbyotic eyes and get migraines with smaller monitors. Tizen 8th gen TV - normally very good for this
![whitescreen](https://user-images.githubusercontent.com/38320370/146040170-ad51ff37-647b-40d9-ba4a-d862920bec42.png)
.

**Comment by ymauray** [comment]
Hello, thanks for your message.

I do not know if this is something I can fix on my side. This looks like a driver problem, and I haven't found anything about disabling HW accel for a flutter app.

I'll keep this issue open for a while, in case I find something after the end-of-year break.

**Comment by TaliskerMan** [comment]
Thank Yannick,

I did look into this a bit and it appears that there "should" be a way to
enable software rendering, though I am no developer here. Take the time and
enjoy the holiday season. This is something I find with my Nvidia drivers
and hardware acceleration, not sure why some apps freak out while others
have no issues at all.

Wishing you and yours a very happy, healthy and safe holiday season. Take a
rest, relax and enjoy the time away. This is a journey, not a destination.
I'm just amazed that this app looks so really beautiful and you've done
great work. Might work on my laptop better (different graphics) - though I
won't know until I get to it when I travel during the Holidays.

Have a nice day!

Chuck

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickgui/commit/3c23106d32f6c7e21ecb4f5ff06f0dc119d25ec6
