### ISSUE TITLE
Can we add ArcoLinux to the list of isos?

### ISSUE THREAD

**Issue by erikdubois** [quickemu-project/quickgui#59]
If yes what do I need to do?

**Comment by marxjohnson** [comment]
The list of available OSs is generated by [quickemu](https://github.com/quickemu-project/quickemu), so you'll need to raise this issue there. There are currently several open pull requests about adding additional OSs, so looking at those might give you some pointers.

**Comment by erikdubois** [comment]
ok you can close it
