### ISSUE TITLE
Leave the icon up to the developers

### ISSUE THREAD

**Issue by erikdubois** [quickemu-project/quickgui#60]
/usr/share/applications/quickgui.desktop

use this code 

Icon=quickgui

no png svg or anything
loose the number (_512) so that icon themes can use their own creation for your application

Test it out and you will see this works.

**Comment by ymauray** [comment]
Thanks for your contribution. I shall have a look after the end-of-year festivities !

**Comment by erikdubois** [comment]
did you check?
Can we close if implemented?
