### ISSUE TITLE
bug: unable to SSH to the guest VM

### ISSUE THREAD

**Issue by thierrybo** [quickemu-project/quickgui#61]
Hi,

I just installed ZorinOs16 with Quickgui 1.2.2/Quickemu 3.11, installed SSH in guest, stop and restarted the guest, Quickgui does not detect SSH server.

`ssh zorinos@localhost -p 22220`

on the host work however.

System:    Kernel: 5.15.0-2-amd64 x86_64 bits: 64 Desktop: Openbox 3.6.1
           Distro: Devuan GNU/Linux 5 (daedalus/ceres)

**Comment by flexiondotorg** [comment]
I am not able to reproduce this issue.

**Comment by MrHappy** [comment]
I have the same issue, but on latest Archlinux.
Manually ssh-ing to the guest works fine (on the port in archlinux-latest.ports).

**Comment by flexiondotorg** [comment]
I've just tested with the Quickemu 1.2.9 release candidate. Started Ubuntu 22.04 and Ubuntu 24.04 guest VMs that have OpenSSH server installed and running.

I can connect to both via:

- `ssh martin@localhost -p 22222`
- `ssh martin@localhost -p 22223`

Quickgui reports "SSH server not detected on guest" for both guest VMs.
