### ISSUE TITLE
No icons for Mint and NixOS flavours

### ISSUE THREAD

**Issue by daPhipz** [quickemu-project/quickgui#64]
There are no icons shown for Linux Mint MATE and XFCE, as well as NixOS GNOME, KDE and Minimal.

However, there is an icon for both these distros in https://github.com/quickemu-project/quickemu-icons - do you know what's the issue here?
Will also affect the following distros, once their PRs get merged:
- Manjaro: https://github.com/quickemu-project/quickemu/pull/296
- MX Linux: https://github.com/quickemu-project/quickemu/pull/292

**Comment by philclifford** [comment]
I see the same issue: with running quickgui from a terminal I see the following:
```flutter: Failed to find definition for url(#b)
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1156)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:977)
flutter: #2      reportMissingDef (package:flutter_svg/src/utilities/errors.dart:5)
flutter: #3      _getDefinitionPaint (package:flutter_svg/src/svg/xml_parsers.dart:164)
flutter: #4      parseFill (package:flutter_svg/src/svg/xml_parsers.dart:267)
flutter: #5      parseStyle (package:flutter_svg/src/svg/xml_parsers.dart:492)
flutter: #6      SvgParserState.addShape (package:flutter_svg/src/svg/parser_state.dart:924)
flutter: #7      SvgParserState.startElement (package:flutter_svg/src/svg/parser_state.dart:949)
flutter: #8      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:850)
flutter: <asynchronous suspension>
flutter: #9      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #10     Svg.fromSvgString (package:flutter_svg/svg.dart:131)
flutter: <asynchronous suspension>
flutter: #11     Svg.svgPictureStringDecoder (package:flutter_svg/svg.dart:84)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```
with the last repeating 26 more times. The output appears consistently only on first selecting to choose OS for a new machine, and only appears once (i.e. not repeating if you navigate elsewhere and later return to that menu).

**Comment by daPhipz** [comment]
I suspect this to be the the root cause:

Icons are stored in a directory tree like this:

```
/png/DISTRO/icon-variant.png  # For SVGs: s/png/svg/
```

...where DISTRO is the "non-friendly" name of a distro.

For Linux Mint, this name would be `linuxmint`, except where there is a specific icon for a variant (e.g. the icon for Mint Cinnamon is called `linuxmint-cinnamon`).
Since the Cinnamon edition is the only one with a functioning icon, I suspect that Quickgui is expecting an icon called `linuxmint-xfce` and `linuxmint-mate` for the other ones. But we don't have special icons for these spins, just the generic Mint logo.

I guess that Quickgui should check for a special case first and (if not available) fall back to a more generic icon.
@ymauray @marxjohnson Are you ok with the following naming convention (again, for the SVG path just swap out PNG)?

```
/png/linuxmint/icon-variant.png  # This is the generic icon, used when no other icon is available
/png/linuxmint-xfce/icon-variant.png. # This is the icon for the XFCE edition. Other DEs will be appended similarly, with a hyphen ("-")
```

Gosh, I hope I got my point across. English is not my first language, sorry for the wall of text!

**Comment by ymauray** [comment]
I see what you mean. I'll have a look at that soon, and I'll get in sync with the `quickemu-icons` project. I copy the icons from them, there's no automatic link between the projects.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickgui/commit/208d4f8dc9663b45298cc5f6d3075a250b2f870a
