### ISSUE TITLE
Unable to launch quickgui

### ISSUE THREAD

**Issue by Himanshu-kumar-gupta** [quickemu-project/quickgui#69]
Today I updated the quickgui and after the update I was unable to launch quickgui.
I tried launching from terminal by following command :
/usr/bin/quickgui 

But I get following error after executing command :

/usr/bin/quickgui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/quickgui)

My distro is Linux mint cinnamon 20.3

**Comment by ymauray** [comment]
Hi, thanks for the report. The binary has been re-built, and version 1.2.4-1 has been pushed to the PPA. Can you update and let me know if this issue is resolved ? Thank !

**Comment by mastertheif** [comment]
I had the same issue and the fix worked for me.

**Comment by Himanshu-kumar-gupta** [comment]
Thank you bro for providing the fix so fast, it worked for me and quickgui is launching flawlessly.
