### ISSUE TITLE
Unable to launch Quickgui after replacing the video card

### ISSUE THREAD

**Issue by eson57** [quickemu-project/quickgui#80]
Can't start quickgui after replacing video card, on Linux Mint 20.3.
Here's the cli outcome.
```
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Avbruten (SIGABRT) (minnesutskrift skapad)
```
I've tried reinstall quickgui with no success. Quickemu/quickget works the same as before.

**Comment by ymauray** [comment]
That doesn't look specific to Quickgui. Does that happen with other Flutter apps ?

**Comment by eson57** [comment]
Sorry, I don't think I have other flutter apps and besides that, I've upgraded to Linux Mint 21 since then and now it works perfectly well. Closing this issue.
