### ISSUE TITLE
There's no longer a non-deb linux release of quickgui since 1.2.6

### ISSUE THREAD

**Issue by seltzered** [quickemu-project/quickgui#90]
Hi! I've been happily using quickgui since last spring, and at the time was on Ubuntu and just installed it via the apt package. 

More recently I started using Fedora and noticed since 1.2.6 there's only .deb packages distributed. What would be the best path to support other distributions - should one write a homebrew/linuxbrew formula to build from source? Noticing a challenge is flutter itself doesn't support installing itself that well outside of ubuntu (see https://github.com/flutter/flutter/issues/9401 & https://github.com/flutter/flutter/issues/25596 ).

Thanks,
Vivek

**Comment by seltzered** [comment]
( did briefly try to see if `alien` would work in converting the latest deb package, trying `sudo alien --to-rpm quickgui_1.2.8-1_lunar1.0_amd64.deb` ended up with `Control file couldn't be read! at /usr/share/perl5/vendor_perl/Alien/Package/Deb.pm line 234.` )

**Comment by ozky84** [comment]
Ubuntu changed to deb packages to use zstd compression and alien doesn't supports it,try Focal package convert with alien as Focal use tar.xz compression in deb packages.....

**Comment by StudioCrash** [comment]
I've been trying to install quickgui from the AUR on endeavour os using yay. Yay is a command line utility that automates the process of downloading and building package binaries from source.  Awesome that it's there, but I get these errors during build.:

> Flutter failed to create a directory at "/opt/flutter/bin/cache/downloads".
> Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the
> current user.
> 
> 
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: quickgui

**Comment by ben-alkov** [comment]
Attempting to build quickgui from source, using WORKING flutter from GitHub source, consistently produces the utterly nonsensical

```
Resolving dependencies...
Because every version of flutter_localizations from sdk depends on intl 0.18.0 and quickgui depends on intl ^0.17.0,
  flutter_localizations from sdk is forbidden.
So, because quickgui depends on flutter_localizations from sdk, version solving failed.
```

**Comment by YasirRWebDesigner** [comment]
> flutter_localizations

go to quickgui/pubspec.yaml and on line 24 change ` intl: ^0.17.0 ` to  that of current version shown in error for me it was ` intl: ^0.18.1 ` .

However now I get a new error 

`
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Building Linux application...                                           
Unable to generate build files
`


I'll update the comment once I fix it.

**Comment by YasirRWebDesigner** [comment]
> Attempting to build quickgui from source, using WORKING flutter from GitHub source, consistently produces the utterly nonsensical
> 
> ```
> Resolving dependencies...
> Because every version of flutter_localizations from sdk depends on intl 0.18.0 and quickgui depends on intl ^0.17.0,
>   flutter_localizations from sdk is forbidden.
> So, because quickgui depends on flutter_localizations from sdk, version solving failed.
> ```

> flutter_localizations

go to quickgui/pubspec.yaml and on line 24 change ` intl: ^0.17.0 ` to  that of current version shown in error for me it was ` intl: ^0.18.1 ` .

**Comment by ItsRogueRen** [comment]
Its 2024 now and there are still no rpm or appimage packages, is there a reason for this? Is there some technical limitation the is preventing these from being released?
