### ISSUE TITLE
1.2.4 binary release: clicking executable results in blank quickgui window, works okay from CLI though

### ISSUE THREAD

**Issue by seltzered** [quickemu-project/quickgui#91]
Hi, I'm currently using quickgui 1.2.4 on fedora (see issue https://github.com/quickemu-project/quickgui/issues/90 as to why) and noticed that quickgui shows up blank when trying to just click and execute it from gnome files:

![image](https://user-images.githubusercontent.com/297435/207672696-e2656b36-ff1d-4567-8a8f-9e15bbdcf7a8.png)

...but things work fine when launching from the command line: 

![image](https://user-images.githubusercontent.com/297435/207673271-d647f4d4-b6c1-479e-9598-c2fc2b98ae22.png)

Any idea why? Rather curious as I notice similar quirks in developing an electron app too, wondering if there's a sandboxing difference or something.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/quickemu-project/quickgui/commit/3c23106d32f6c7e21ecb4f5ff06f0dc119d25ec6
