### ISSUE TITLE
No existing machines in Manage existing machines

### ISSUE THREAD

**Issue by blusewill** [quickemu-project/quickgui#92]
So I downloaded kali-weekly on quickgui and When I trying to manage Kali Linux that I just Downloaded it doesn't work for some reason I don't know if that is a bug or not, Hope can fix it as soon as possible 

Downloaded Image
![image](https://user-images.githubusercontent.com/62820836/208950667-b04c803b-a4c4-4386-b424-a436af07b4d7.png)

Doesn't show up on the Manager
![image](https://user-images.githubusercontent.com/62820836/208950750-c8d453bb-d6c0-46f1-91a1-204ce6df20b8.png)

**Comment by madroots** [comment]
Same here :/ unusable

**Comment by daxisunder** [comment]
Same here, on Arch-Hyprland.
