### ISSUE TITLE
Can XeroLinux be added to list ?

### ISSUE THREAD

**Issue by DarkXero-dev** [quickemu-project/quickgui#93]
Hello

I am the creator of [XeroLinux](https://xerolinux.xyz) and I was wondering can it be added to list of available ones to install in QuickGUI ?

Thanks ;)

**Comment by philclifford** [comment]
It can maybe, when someone adds it to QuickEmu ...  Thanks.

**Comment by zen0bit** [comment]
@TechXero

So

Why you not add yourself? Your child

It's very easy and take few minutes...

**Comment by zen0bit** [comment]
i mean like your project XeroLinux

**Comment by zen0bit** [comment]
Me to..

I am not even distro maintainer and added some distros to quickemu (And more are waiting..)

Bash is enough...

just take a look at [raw quickget](https://raw.githubusercontent.com/quickemu-project/quickemu/master/quickget)

But I am not speaking about quickgui, just about quickget and quickemu which are bash scripts ;)

And also my child (skript) quickfzf also in pull requests...

Or: If you provide all links to ISOs

 I can do it..

**Comment by TechXero** [comment]
Well my ISO is on a torrent... So dunno if that helps...
https://fosstorrents.com/distributions/xerolinux/

**Comment by zen0bit** [comment]
i think quickget dont support torrents (yet)

Any link to direct download? github, sourceforge, ... anywhere?

**Comment by zen0bit** [comment]
https://github.com/quickemu-project/quickemu/pull/667

**Comment by TechXero** [comment]
https://sourceforge.net/projects/xerolinux/files/Releases/

**Comment by zen0bit** [comment]
> https://sourceforge.net/projects/xerolinux/files/Releases/

Already founded and created pull request with XeroLinux added..

You can try it before get merged in my:
[prerelease](https://github.com/oSoWoSo/quickfzf/releases/tag/4.6.0.7)

**Comment by zen0bit** [comment]
I am not remmember how it is with quickgui.

It will maybe need more work before XeroLinux will be added to quickgui...
(But I am not using it so...)

**Comment by TechXero** [comment]
It's ok. I don't use Quick Emu or Gui either was a user request. Can wait... Thanks a ton...

**Comment by zen0bit** [comment]
I will try XeroLinux, since I added to quickget and already downloaded...
will see

**Comment by zen0bit** [comment]
@TechXero
Could you provide your distro logo icon in svg?
(png is nice but...)

**Comment by TechXero** [comment]
Yeah sure... Use the white+Purple one...

https://wormhole.app/y14lr#fYPj5XSbVHLwwg2WtV5TjQ

**Comment by zen0bit** [comment]
thank you

PS:
I put out first public alpha version of my quickgui
check it
[repo](https://github.com/oSoWoSo/yadEmu)

See it in action on youtube...
[quickgui](https://www.youtube.com/watch?v=JtjIseqZMkQ)

if you preffer command line...
[quicktui](https://www.youtube.com/watch?v=gJ5hqYEskOw)

**Comment by flexiondotorg** [comment]
XeroLinux is no longer being distributed as a Linux distribution, it is now a configuration tool.
