### ISSUE TITLE
bug: can't scroll through list of distros on KDE

### ISSUE THREAD

**Issue by bckelley** [quickemu-project/quickgui#94]
Installed in Kubuntu 22.04 and quickgui doesn't scroll through the list of distros, also would like to add can't exit from fullscreen mode

**Comment by ryanfantus** [comment]
I have the same issues on Kubuntu 22.04 however I am using KDE 5.25 (in case it matters, Kubuntu ships with 5.24).

**Comment by peterhavener** [comment]
Same problem here! Cannot scroll the distro list. Running Kubuntu 22.04.3 LTS and Plasma 5.24.7

**Comment by bot66** [comment]
ubuntu 22.04.2, can't exit fullscreen, `shift+f11` and `ctrl+alt+f` do not work, need shutdown the VM to exit fullscreen.

**Comment by flexiondotorg** [comment]
Tested on KDE Neon (22.04) and Kubuntu 24.04. This is fixed via https://github.com/quickemu-project/quickgui/commit/245c1f5251ce3e4ab24d2daecf3de645ec9f5a16

This will feature in Quickemu 1.2.9, which will be out very soon.

**Comment by handtrixx** [comment]
still not fixed :-(
